name: Cypress Tests

on:
  push:
    branches:
      - For_Task_15_3

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cy:run_chrome_headed -- --spec cypress/e2e/Custom_scenarious/guru_testing.cy.js Task_12.cy.js mainPage.cy.js newborn.cy.js